import { z } from "zod";

// ─── Schema version ───────────────────────────────────────────────────────────
export const SCHEMA_VERSION = "1.0";

// ─── String helpers ───────────────────────────────────────────────────────────

const esc = (max) =>
  z.string().max(max).transform((v) =>
    v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#039;").trim()
  );

// Raw — not HTML-escaped. For code and Mermaid source.
const raw = (max) => z.string().max(max).transform((v) => v.trim());

const S   = esc(300);   // short label
const M   = esc(800);   // medium text
const L   = esc(4000);  // long prose
const URL = esc(500);   // URLs / paths

// ─── Block Definitions ────────────────────────────────────────────────────────

const CoverBlock = z.object({
  type:     z.literal("cover"),
  title:    S,
  subtitle: S.optional(),
  author:   S.optional(),
  date:     S.optional(),
});

// TOC is auto-generated by the renderer — no content fields needed
const TocBlock = z.object({ type: z.literal("toc") });

const HeadingBlock = z.object({
  type:  z.literal("heading"),
  text:  S,
  level: z.number().int().min(1).max(3).default(1),
  id:    z.string().max(100).optional(),
});

const ParagraphBlock = z.object({
  type: z.literal("paragraph"),
  text: L,
});

const BulletsBlock = z.object({
  type:    z.literal("bullets"),
  title:   S.optional(),
  ordered: z.boolean().default(false),
  items:   z.array(M).min(1).max(20),
});

const StatsBlock = z.object({
  type:  z.literal("stats"),
  title: S.optional(),
  items: z.array(z.object({ label: S, value: esc(200) })).min(1).max(6),
});

const TableBlock = z.object({
  type:    z.literal("table"),
  title:   S.optional(),
  columns: z.array(S).min(1).max(10),
  rows:    z.array(z.array(M).min(1).max(10)).min(1).max(50),
});

const MermaidBlock = z.object({
  type:         z.literal("mermaid"),
  title:        S.optional(),
  diagram_type: z.enum(["flowchart", "sequence", "er", "gantt", "class", "state", "mindmap", "generic"]).default("generic"),
  source:       raw(8000),
});

const CodeBlock = z.object({
  type:        z.literal("code"),
  title:       S.optional(),
  language:    z.string().max(30).default("text"),
  code:        raw(10000),
  description: M.optional(),
});

const ApiTableBlock = z.object({
  type:      z.literal("api_table"),
  title:     S.optional(),
  endpoints: z.array(z.object({
    method:      z.enum(["GET", "POST", "PUT", "PATCH", "DELETE"]),
    path:        esc(200),
    description: M,
    auth:        z.boolean().default(true),
    status:      z.enum(["stable", "beta", "deprecated"]).default("stable"),
    body:        S.optional(),
    response:    S.optional(),
  })).min(1).max(20),
});

const SchemaBlock = z.object({
  type:   z.literal("schema"),
  title:  S.optional(),
  tables: z.array(z.object({
    name:    S,
    columns: z.array(z.object({
      name:        S,
      type:        esc(80),
      constraints: S.optional(),
      description: M.optional(),
    })).min(1).max(25),
  })).min(1).max(5),
});

const RiskMatrixBlock = z.object({
  type:  z.literal("risk_matrix"),
  title: S.optional(),
  risks: z.array(z.object({
    name:       M,
    likelihood: z.enum(["low", "medium", "high"]),
    impact:     z.enum(["low", "medium", "high"]),
    mitigation: M.optional(),
    owner:      S.optional(),
  })).min(1).max(15),
});

const DecisionLogBlock = z.object({
  type:      z.literal("decision_log"),
  title:     S.optional(),
  decisions: z.array(z.object({
    id:        S,
    decision:  M,
    rationale: L,
    status:    z.enum(["accepted", "rejected", "pending", "superseded"]),
    date:      S.optional(),
    owner:     S.optional(),
  })).min(1).max(20),
});

const PrdBlock = z.object({
  type:         z.literal("prd"),
  title:        S.optional(),
  requirements: z.array(z.object({
    id:          S,
    requirement: M,
    priority:    z.enum(["must", "should", "could", "wont"]),
    status:      z.enum(["open", "in-progress", "done", "cancelled"]).default("open"),
    notes:       M.optional(),
  })).min(1).max(30),
});

const QuoteBlock = z.object({
  type:   z.literal("quote"),
  text:   M,
  source: S.optional(),
});

const TimelineBlock = z.object({
  type:   z.literal("timeline"),
  title:  S.optional(),
  events: z.array(z.object({
    date:        S,
    title:       S,
    description: M.optional(),
    status:      z.enum(["done", "active", "upcoming"]).default("upcoming"),
  })).min(1).max(20),
});

const CalloutBlock = z.object({
  type:    z.literal("callout"),
  variant: z.enum(["info", "warning", "tip", "caution", "success"]).default("info"),
  title:   S.optional(),
  text:    M,
});

const DividerBlock = z.object({ type: z.literal("divider") });

const ConclusionBlock = z.object({
  type:   z.literal("conclusion"),
  title:  S,
  points: z.array(M).min(1).max(10),
});

// ─── Chart ────────────────────────────────────────────────────────────────────
// Numbers get drawn, not listed. `values` is parallel to `categories`.
const ChartBlock = z.object({
  type:       z.literal("chart"),
  chart_type: z.enum(["bar", "column", "line", "donut", "progress"]).default("column"),
  title:      S.optional(),
  subtitle:   S.optional(),
  unit:       esc(24).optional(),          // "%", "ms", "$" — suffixed onto labels
  categories: z.array(S).min(1).max(12),
  series:     z.array(z.object({
    name:   S,
    values: z.array(z.number()).min(1).max(12),
  })).min(1).max(8),
  takeaway:   M.optional(),                // the one sentence the chart is making
});

// ─── Comparison (A vs B) ──────────────────────────────────────────────────────
const ComparisonBlock = z.object({
  type:  z.literal("comparison"),
  title: S.optional(),
  left:  z.object({ title: S, items: z.array(M).min(1).max(6) }),
  right: z.object({ title: S, items: z.array(M).min(1).max(6) }),
});

// ─── Two-column idea clusters ─────────────────────────────────────────────────
const TwoColBlock = z.object({
  type:    z.literal("two_col"),
  title:   S.optional(),
  columns: z.array(z.object({
    title: S,
    text:  M.optional(),
    items: z.array(M).max(6).default([]),
  })).length(2),
});

// ─── Ordered process ──────────────────────────────────────────────────────────
const StepsBlock = z.object({
  type:  z.literal("steps"),
  title: S.optional(),
  steps: z.array(z.object({
    title:       S,
    description: M.optional(),
  })).min(2).max(6),
});

// ─── Full-bleed section divider ───────────────────────────────────────────────
const SectionBreakBlock = z.object({
  type:     z.literal("section_break"),
  title:    S,
  subtitle: S.optional(),
  number:   esc(8).optional(),
});

// ─── Image block (for Asset Manager — Phase 2) ────────────────────────────────
const ImageBlock = z.object({
  type:    z.literal("image"),
  src:     URL,
  alt:     S.optional(),
  caption: S.optional(),
  width:   z.enum(["full", "half", "third"]).default("full"),
});

// ─── Discriminated union of all blocks ────────────────────────────────────────

export const Block = z.discriminatedUnion("type", [
  CoverBlock,
  TocBlock,
  HeadingBlock,
  ParagraphBlock,
  BulletsBlock,
  StatsBlock,
  TableBlock,
  MermaidBlock,
  CodeBlock,
  ApiTableBlock,
  SchemaBlock,
  RiskMatrixBlock,
  DecisionLogBlock,
  PrdBlock,
  QuoteBlock,
  TimelineBlock,
  CalloutBlock,
  DividerBlock,
  ConclusionBlock,
  ChartBlock,
  ComparisonBlock,
  TwoColBlock,
  StepsBlock,
  SectionBreakBlock,
  ImageBlock,
]);

// ─── Section ──────────────────────────────────────────────────────────────────
// A section is the unit of LAYOUT. The writer emits flat blocks; the composer
// groups them into sections and hands each one to a layout. The HTML renderer
// turns a section into one or more pages; the PPTX exporter turns the same
// section into one or more slides. One tree, two media.
export const SectionSchema = z.object({
  id:     z.string().max(60),
  title:  S.optional(),
  layout: z.string().max(30).default("bullets"),
  blocks: z.array(Block).min(1).max(30),
  notes:  L.optional(),          // speaker notes — PPTX only, ignored by PDF
});

// ─── Top-level document ───────────────────────────────────────────────────────

export const DocumentSchema = z.object({
  version: z.string().default(SCHEMA_VERSION),
  meta: z.object({
    title:   S,
    author:  S.optional(),
    theme:   z.enum(["professional", "dark", "minimal", "github"]).default("professional"),
    subject: S.optional(),
  }),
  blocks:   z.array(Block).min(1).max(200),
  // Populated by the composer. Renderers prefer `sections` and fall back to the
  // flat `blocks` stream, so a document that skipped composition still renders.
  sections: z.array(SectionSchema).max(60).optional(),
});

/** @typedef {import("zod").infer<typeof DocumentSchema>} Document */
/** @typedef {import("zod").infer<typeof SectionSchema>} Section */
/** @typedef {import("zod").infer<typeof Block>} Block */

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Validate raw JSON against the DocumentSchema.
 * @param {unknown} raw
 * @returns {{ doc: Document } | { error: string }}
 */
export function validateDocument(raw) {
  const result = DocumentSchema.safeParse(raw);
  if (result.success) return { doc: result.data };
  const summary = result.error.issues
    .slice(0, 5)
    .map((i) => `${i.path.join(".")}: ${i.message}`)
    .join("; ");
  return { error: summary };
}

/**
 * Extract first JSON object from a raw LLM string (strips markdown fences).
 * @param {string} str
 * @returns {unknown | null}
 */
export function extractJson(str) {
  const stripped = str.replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim();
  const start = stripped.indexOf("{");
  const end   = stripped.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try { return JSON.parse(stripped.slice(start, end + 1)); }
  catch { return null; }
}
