/** @type {import("./index.js").Theme} */
export const minimal = {
  name:          "minimal",
  accent:        "#111827",
  accentDark:    "#000000",
  accentLight:   "#F9FAFB",
  accentBorder:  "#E5E7EB",
  bg:            "#FFFFFF",
  coverBg:       "#FFFFFF",
  coverText:     "#111827",
  coverMuted:    "#6B7280",
  bodyText:      "#111827",
  mutedText:     "#9CA3AF",
  cardBg:        "#F9FAFB",
  cardAlt:       "#F3F4F6",
  codeBg:        "#1F2937",
  codeText:      "#F9FAFB",
  statBg:        "#F9FAFB",
  statCard:      "#FFFFFF",
  statValue:     "#111827",
  conclusionBg:  "#111827",
  borderRadius:  "4px",
  cardShadow:    "none",
  headingFont:   "Inter",
  bodyFont:      "Inter",
  monoFont:      "JetBrains Mono",
  googleFonts:   "Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500",
};
