/** @type {import("./index.js").Theme} */
export const professional = {
  name:          "professional",
  accent:        "#2563EB",
  accentDark:    "#1D4ED8",
  accentLight:   "#EFF6FF",
  accentBorder:  "#BFDBFE",
  bg:            "#FFFFFF",
  coverBg:       "#0F172A",
  coverText:     "#FFFFFF",
  coverMuted:    "#94A3B8",
  bodyText:      "#1E293B",
  mutedText:     "#64748B",
  cardBg:        "#F8FAFC",
  cardAlt:       "#EFF6FF",
  codeBg:        "#0F172A",
  codeText:      "#E2E8F0",
  statBg:        "#0F172A",
  statCard:      "#1E3A5F",
  statValue:     "#60A5FA",
  conclusionBg:  "#2563EB",
  borderRadius:  "8px",
  cardShadow:    "0 1px 3px rgba(0,0,0,0.08)",
  headingFont:   "Sora",
  bodyFont:      "Inter",
  monoFont:      "JetBrains Mono",
  googleFonts:   "Inter:wght@400;500;600;700&family=Sora:wght@600;700;800&family=JetBrains+Mono:wght@400;500",
};
